import type { Metadata } from 'next';
import { Providers } from '@/components/providers';
import localFont from 'next/font/local';
import '@/styles/globals.css';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { cn } from '@/lib/utils';
import ScrollToTopButton from '@/components/layout/ScrollToTopButton';

// 폰트 설정
const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/image/logo/logo-white.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body
        className={cn('antialiased', pretendard.className)}
        suppressHydrationWarning={true}
      >
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Header />

            <main className="flex-1 bg-white content-center">
              {children}
              <ScrollToTopButton />
            </main>

            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
