import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Providers } from '@/components/providers';
import '@/styles/globals.css';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning={true}>
        <Providers>
          {/* 전체 화면 고정, 스크롤 방지 */}
          <div className="flex flex-col h-screen overflow-hidden">
            <Header />

            {/* 
               overflow-y-auto: 내용이 부모 높이를 넘칠 때만 스크롤바 생성
               scrollbar-hide: (선택사항) 스크롤바 디자인이 보기 싫다면 클래스 추가 가능
            */}
            <main className="flex-1 overflow-y-auto bg-white">{children}</main>

            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
