# infra/envs/prod/app/helm-values/loki-values.yaml

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage:
    type: s3
    bucketNames:
      chunks: "${loki_bucket_name}" # 테라폼에서 주입
      ruler: "${loki_bucket_name}"
      admin: "${loki_bucket_name}"
    s3:
      region: ap-northeast-2
      s3ForcePathStyle: true

  serviceAccount:
    create: true
    name: loki
    annotations:
      # 테라폼에서 주입하는 동적 ARN
      eks.amazonaws.com/role-arn: "${loki_role_arn}"

deploymentMode: SingleBinary

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi