# helm-values/service-scg.yaml
apiVersion: v1
kind: Service
metadata:
  name: on-race-scg-service
  namespace: on-race-prod
spec:
  selector:
    app: t6-on-race-scg # SCG 파드의 레이블과 일치해야 함
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP # ALB가 직접 파드 IP로 쏘기 때문에 ClusterIP면 충분합니다.