import { Notice } from '@/features/notice/types/notice';

export const MOCK_NOTICES: Notice[] = [
  {
    id: 1,
    category: '공지',
    title: '2026 JTBC 서울 마라톤 공식 티켓 오픈 안내',
    date: '2024.09.20',
    views: 1240,
    isPinned: true,
  },
  {
    id: 2,
    category: '이벤트',
    title: '러너스 허브 가을맞이 크루 모집 지원금 이벤트',
    date: '2024.09.18',
    views: 856,
    isPinned: true,
  },
  {
    id: 3,
    category: '공지',
    title: '서비스 시스템 점검 안내 (10/01 02:00 ~ 06:00)',
    date: '2024.09.15',
    views: 432,
    isPinned: false,
  },
  {
    id: 4,
    category: '결과',
    title: '제 22회 서울 국제 마라톤 부문별 수상자 발표',
    date: '2024.09.10',
    views: 2105,
    isPinned: false,
  },
  {
    id: 5,
    category: '안내',
    title: '마라톤 기록증 발급 및 배송 프로세스 변경 안내',
    date: '2024.09.05',
    views: 766,
    isPinned: false,
  },
  {
    id: 6,
    category: '공지',
    title: '개인정보 처리방침 개정 사전 안내',
    date: '2024.09.01',
    views: 230,
    isPinned: false,
  },
  {
    id: 7,
    category: '이벤트',
    title: '첫 완주 기념 메달 각인 서비스 신청 페이지 오픈',
    date: '2024.08.28',
    views: 1540,
    isPinned: false,
  },
];
