import { MarathonEvent } from '@/features/schedule/types/schedule';

export const MARATHON_DATA: MarathonEvent[] = [
  {
    id: 1,
    title: '서울 마라톤 대회 2026',
    thumbnail: '',
    status: '응모중',
    location: '서울',
    month: '4',
    day: '15',
    date: '2026.04.15',
    courses: ['Full', 'Half', '10km'],
  },
  {
    id: 2,
    title: '부산 바다 러닝 페스티벌',
    thumbnail: '',
    status: '신청중',
    location: '부산',
    month: '5',
    day: '20',
    date: '2026.05.20',
    courses: ['Half', '10km', '5km'],
  },
  {
    id: 3,
    title: '제주 올레길 마라톤',
    thumbnail: '',
    status: '응모대기',
    location: '제주',
    month: '6',
    day: '10',
    date: '2026.06.10',
    courses: ['Full', 'Half'],
  },
  {
    id: 4,
    title: '대구 컬러런',
    thumbnail: '',
    status: '대기중',
    location: '대구',
    month: '7',
    day: '05',
    date: '2026.07.05',
    courses: ['5Km', '10km'],
  },
];
