plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')

    // CORE
    implementation 'org.springframework.boot:spring-boot-starter-web'
    runtimeOnly 'com.mysql:mysql-connector-j'

    // [인프라 추가] DATABASE & CACHE
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'com.github.ben-manes.caffeine:caffeine'

    // UTILS
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // TEST
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'com.h2database:h2'

    // OBSERVABILITY
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    // [인프라 추가] Monitoring & Metrics
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // QUERYDSL
    annotationProcessor 'com.querydsl:querydsl-apt:5.1.0:jakarta'
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'
}