server {
    listen       8080; # 80에서 8080으로 수정
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # 헬스 체크를 위한 경로 (필요 시)
    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}