name: "On-Race-Infra-CD"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
  AWS_REGION: ap-northeast-2
  CLUSTER_NAME: t6-on-race-prod-cluster

on:
  push:
    branches: [ "feat/infra/init-monitoring" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    # [추가] OIDC 인증 권한
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # [수정] Role 기반 인증으로 변경
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600 # 세션 유효 시간을 2시간(7200초)으로 연장

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Base Layer Apply
        working-directory: ./infra/envs/prod/base
        run: |
          terraform init
          terraform apply -auto-approve

      - name: App Layer - EKS & Network Core
        working-directory: ./infra/envs/prod/app
        run: |
          terraform init
          terraform apply -auto-approve -target=module.eks

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: App Layer - Core Infrastructure
        working-directory: ./infra/envs/prod/app
        run: |
          terraform apply -auto-approve \
            -target=module.lb_controller_irsa \
            -target=helm_release.lb_controller \
            -target=aws_eks_addon.ebs_csi \
            -target=kubernetes_storage_class_v1.gp3_default \
            -target=module.karpenter \
            -target=helm_release.karpenter

      - name: Wait for Infrastructure Stabilization
        run: sleep 120

      - name: App Layer - Full Final Apply
        working-directory: ./infra/envs/prod/app
        run: terraform apply -auto-approve
      
      # KEDA ScaledObject 강제 적용 단계
      - name: Apply KEDA ScaledObject via Kubectl
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: keda.sh/v1alpha1
          kind: ScaledObject
          metadata:
            name: on-race-api-scaler
            namespace: t6-on-race-prod
          spec:
            scaleTargetRef:
              name: on-race-api
            minReplicaCount: 2
            maxReplicaCount: 300
            triggers:
              - type: prometheus
                metadata:
                  serverAddress: http://t6-on-race-prometheus-server.monitoring.svc.cluster.local:80
                  metricName: onrace_tps_requests_total
                  threshold: "50"
                  query: "sum(rate(onrace_tps_requests_total{result=\"allowed\"}[1m]))"
          EOF